apiVersion: v1
kind: Service
metadata:
  name: challenge-web
  namespace: stone
  labels:
    app: challenge-web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:273539623895:certificate/66e42167-2b62-4aec-b317-bee5cc4eacfd"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer 
  selector:
    app: challenge-web
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-web
  namespace: stone
  labels:
    app: challenge-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: challenge-web
  template:
    metadata:
      labels:
        app: challenge-web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: challenge-web
        image: 273539623895.dkr.ecr.us-east-1.amazonaws.com/challenge-web:latest
        env:
          - name: API_HOST
            value: http://challenge-api.stone.svc.cluster.local
        ports:
        - containerPort: 80